apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: mimos-vaultkubenertes-job
  namespace: mimos-net
  annotations:
    fluxcd.io/automated: "false"
spec:
  interval: 1m
  releaseName: mimos-vaultkubenertes-job
  chart:
    spec:
      interval: 1m
      sourceRef:
        kind: GitRepository
        name: flux-local
        namespace: flux-local
      chart: platforms/hyperledger-fabric/charts/vault_kubernetes
  values:
    metadata:
      name: mimos
      component_type: orderer
      namespace: mimos-net    
      images:
        alpineutils: index.docker.io/hyperledgerlabs/alpine-utils:1.0

    vault:
      reviewer_service: vault-reviewer
      role: vault-role
      address: http://10.1.69.214:32603/
      authpath: localmimos-net-auth
      policy: vault-crypto-orderer-mimos-net-ro
      secret_path: secretsv2
      serviceaccountname: vault-auth
      imagesecretname: regcred
    
    k8s:
      kubernetes_url: https://10.1.69.214:6443
